// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77YY6vq8oSOvsaZsyl-Qlvd9FGVZLsZM',
    appId: '1:663845520137:web:b8bb23f6bfac3e7690c9d8',
    messagingSenderId: '663845520137',
    projectId: 'project2-74c56',
    authDomain: 'project2-74c56.firebaseapp.com',
    storageBucket: 'project2-74c56.firebasestorage.app',
    measurementId: 'G-5NRQSS3VCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfBenfpZo9GBn4mhipj7mh7M3XOUrUlJs',
    appId: '1:663845520137:android:584d4ce5efa779b990c9d8',
    messagingSenderId: '663845520137',
    projectId: 'project2-74c56',
    storageBucket: 'project2-74c56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPSxtopeP79A-5Jh_gHQdgmaTlz85K38',
    appId: '1:663845520137:ios:356354d22ce7ec8d90c9d8',
    messagingSenderId: '663845520137',
    projectId: 'project2-74c56',
    storageBucket: 'project2-74c56.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPSxtopeP79A-5Jh_gHQdgmaTlz85K38',
    appId: '1:663845520137:ios:356354d22ce7ec8d90c9d8',
    messagingSenderId: '663845520137',
    projectId: 'project2-74c56',
    storageBucket: 'project2-74c56.firebasestorage.app',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77YY6vq8oSOvsaZsyl-Qlvd9FGVZLsZM',
    appId: '1:663845520137:web:0159ab8b1c2d81b290c9d8',
    messagingSenderId: '663845520137',
    projectId: 'project2-74c56',
    authDomain: 'project2-74c56.firebaseapp.com',
    storageBucket: 'project2-74c56.firebasestorage.app',
    measurementId: 'G-QKWS8WEEKJ',
  );
}
